language: python
python:
- '2.6'
- '2.7'
script: python instapaperlib/instapaperlib.py
branches:
  only:
  - master
deploy:
  provider: pypi
  user: mrtazz
  password:
    secure: m32BfYp2HRD6DKYpQZQFkyJDPhqJRdaciirLDjihm3Eut1L7fd4oQGkgaQpFYCVh/xlks5W4phTSSO36bCvpDHLkWF5NZChZ/LXdjmIj5C9IUtEhr9bYebRFRkElZ3wbZ0gavjF2oQBGQV5Zix6iac5YIHSCJHMLtxYP51Y+8oo=
  on:
    tags: true
    repo: mrtazz/InstapaperLibrary
